### ISSUE TITLE
CTD after leaving base defense mission

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#503]
Once returned to the cityscape after a base defense mission, as soon as the player clicks play the game CTDs

[save_SuperHuman 1B.zip](https://github.com/OpenApoc/OpenApoc/files/2795581/save_SuperHuman.1B.zip)
Save attached

![image](https://user-images.githubusercontent.com/33913088/51738884-12872a80-2088-11e9-9c52-9f3b3400accb.png)

**Comment by FranciscoDA** [comment]
Could you manage to reproduce this bug on a fresh new game since we merged #499 ?

**Comment by JohnSmith25** [comment]
> Could you manage to reproduce this bug on a fresh new game since we merged #499 ?
> If not maybe it's better to close this for now
I managed to reproduce this bug which still happens if you try to fiddle with the base stuff immediately after a base defense mission. However it doesn't CTD anymore when some time passes (30-60 second maybe).

**Comment by emptyVoid** [comment]
The issue affecting provided save game should definitely be fixed by #499, since the crash happens due to defense turret presence in Cityscape, whereas PR makes sure no defense turrets leave Battlescape.

**Comment by FilmBoy84** [comment]
Can no longer replicate here either
Closing
